import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const ALLOWED_ORIGINS=new Set(['https://kngslhdn.github.io','http://localhost:3000','http://127.0.0.1:5500']);
const headers=(req:Request)=>{const origin=req.headers.get('Origin')||'';return {'Access-Control-Allow-Origin':ALLOWED_ORIGINS.has(origin)?origin:'https://kngslhdn.github.io','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET,OPTIONS','Vary':'Origin','Content-Type':'application/json'}};
const json=(req:Request,b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:headers(req)});
const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!);
const clean=(v:unknown)=>String(v??'').trim();
async function admin(req:Request){const auth=req.headers.get('Authorization')||'';if(!auth.startsWith('Bearer '))return false;const {data:{user},error}=await sb.auth.getUser(auth.slice(7));if(error||!user)return false;const caller=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY')!,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});
const {data:profile}=await caller.from('admin_profiles').select('role,active,property_id').eq('user_id',user.id).maybeSingle();const role=String(profile?.role||'').toUpperCase();return profile?.active&&['ADMIN','MANAGER','SUPERADMIN'].includes(role)?{...profile,db:caller}:false;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});if(req.method!=='GET')return json(req,{error:'Method not allowed'},405);try{const authProfile=await admin(req);if(!authProfile)return json(req,{error:'Admin access denied'},403);const caller=authProfile.db;const propertyId=authProfile.property_id;if(!propertyId&&String(authProfile.role).toUpperCase()!=='SUPERADMIN')return json(req,{error:'Property assignment required'},403);const url=new URL(req.url),pass=clean(url.searchParams.get('pass'));if(!pass)return json(req,{error:'Pass / Vest Number is required.'},400);const {data:entry,error:ee}=await caller.from('visitor_entries').select('id,submission_id,visitor_id,visitor_name_snapshot,phone_snapshot,company_name_snapshot,category_snapshot,visitor_name,visitor_phone,visitor_company_name,visitor_category,work_location,purpose,security_officer_name,pass_vest_number,entry_at,exit_id').eq('pass_vest_number',pass).eq('property_id',propertyId).order('entry_at',{ascending:false}).limit(1).maybeSingle();if(ee)throw ee;if(!entry)return json(req,{error:'Visitor record not found.'},404);const [visitorRes,submissionRes,exitRes]=await Promise.all([caller.from('visitors').select('full_name,phone,company_name,category').eq('id',entry.visitor_id).maybeSingle(),caller.from('submissions').select('submission_id').eq('id',entry.submission_id).maybeSingle(),entry.exit_id?caller.from('visitor_exits').select('exit_at,security_officer_name,pass_vest_number').eq('id',entry.exit_id).maybeSingle():Promise.resolve({data:null,error:null} as any)]);if(visitorRes.error)throw visitorRes.error;if(submissionRes.error)throw submissionRes.error;if(exitRes.error)throw exitRes.error;const v=visitorRes.data||{};return json(req,{data:{submission_id:submissionRes.data?.submission_id||null,visitor_id:entry.visitor_id,visitor:{full_name:entry.visitor_name_snapshot||entry.visitor_name||v.full_name||null,phone:entry.phone_snapshot||entry.visitor_phone||v.phone||null,company_name:entry.company_name_snapshot||entry.visitor_company_name||v.company_name||null,category:entry.category_snapshot||entry.visitor_category||v.category||null},work_location:entry.work_location,purpose:entry.purpose,pass_vest_number:entry.pass_vest_number,security_officer_name:entry.security_officer_name,entry_at:entry.entry_at,exit:exitRes.data?{exit_at:exitRes.data.exit_at,security_officer_name:exitRes.data.security_officer_name,pass_vest_number:exitRes.data.pass_vest_number}:null}})}catch(e){console.error(e);return json(req,{error:e instanceof Error?e.message:'Visitor detail request failed'},500)}});
