-- Import the August 2026 Key Asset audit records supplied as five PDFs.
-- Property is resolved by property_code HIKJ; no generated UUID is hardcoded.
insert into public.key_assets
  (property_id,key_number,key_description,floor,quantity,quantity_detail,category,remarks,source_document,location_department)
select p.id,v.key_number,v.key_description,v.floor,v.quantity,v.quantity_detail,v.category,v.remarks,v.source_document,v.category
from (values
('ENG-1','Adrian','All Area',6,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-10','Yuni T','All Area',2,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-11','Mulyadi','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-12','Budi H','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-13','Yulian Maradona','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-14','Abdul Hakim','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-15','Nobel','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-16','Ahmad Zulkarnain','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-17','Soleman','All Area',5,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-18','Ahmad CH','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-19','Triyono','All Area',8,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-2','Marawali','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-20','Iwan BS','All Area',5,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-21','Rocky','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-22','Agus P','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-23','Bahar','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-24','Dodo','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-25','Deden','All Area',2,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-26','Heru','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-27','Winardi','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-28','Slamet Raharjo','All Area',5,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-29','Cecep','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-3','Ocim','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-30','Rudi','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-31','Wasiran','All Area',4,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-32','Purnomo','All Area',8,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-33','M. Asep','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-34','Herwansyah','All Area',2,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-35','Wahyu','All Area',3,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-36','Abdul Azim','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-4','Afif Sugeng','All Area',2,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-5','Dimas','All Area',2,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-6','Budi S','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-7','Yudi F','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-8','Ari S','All Area',1,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('ENG-9','Ridoi','All Area',2,NULL,'KEY OPERATIONAL ENGINEERING',NULL,'Kunci Engineering (1).pdf'),
('GBR-1','CCTV Room','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.224','Kunci Ballroom (1).pdf'),
('GBR-10','Steel door single kitchen/Dpn hydrolik','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-11','Wood Door Samping VIP Room','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.251','Kunci Ballroom (1).pdf'),
('GBR-12','Glass Door Foyer GBR 1','Lt. 11',4,NULL,'KEY GRAND BALLROOM','Master No. 210-213','Kunci Ballroom (1).pdf'),
('GBR-13','Wood Door Hall A,B,C,D','Lt. 11',8,NULL,'KEY GRAND BALLROOM','Master No 202-209','Kunci Ballroom (1).pdf'),
('GBR-14','Diswashing Steward','Lt.11',1,NULL,'KEY GRAND BALLROOM','Master No.223','Kunci Ballroom (1).pdf'),
('GBR-15','Staff Canteen','Lt. 10',2,NULL,'KEY GRAND BALLROOM','Master No.249','Kunci Ballroom (1).pdf'),
('GBR-16','Banquet Linen','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-17','Staff Locker Male / Female','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.252','Kunci Ballroom (1).pdf'),
('GBR-18','Banquet Sales Office','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.212','Kunci Ballroom (1).pdf'),
('GBR-19','Guest Restroom Male / Female','Lt. 11',2,NULL,'KEY GRAND BALLROOM','Master No.221 & 222','Kunci Ballroom (1).pdf'),
('GBR-2','Store Banquet Bawah Tangga','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.200','Kunci Ballroom (1).pdf'),
('GBR-21','CCTV Access to Sales Office','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.228','Kunci Ballroom (1).pdf'),
('GBR-22','Banquet Store/Samping meter air','Lt. 10',4,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-23','KWH Panel Listrik','Lt. 10',6,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-24','Gembok Panel Hidrolik Lift Besar','Lt. 11',2,NULL,'KEY GRAND BALLROOM','Master No.336','Kunci Ballroom (1).pdf'),
('GBR-26','Drop Off GBR','GF',2,NULL,'KEY GRAND BALLROOM','Master No.260','Kunci Ballroom (1).pdf'),
('GBR-27','Rolling Door Garbage / Kitchen','Lt.10',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-28','Walkthrough Keys','Lt. 11',2,NULL,'KEY GRAND BALLROOM','Master No. 5','Kunci Ballroom (1).pdf'),
('GBR-3','Manager Sales Banquet Office','Lt. 12',1,NULL,'KEY GRAND BALLROOM','Master No.218','Kunci Ballroom (1).pdf'),
('GBR-31','Restroom Male / Female Kontraktor','Lt.10',2,NULL,'KEY GRAND BALLROOM','Master No.31','Kunci Ballroom (1).pdf'),
('GBR-32','Gembok Lift Hidrolik besar','Lt.10',6,NULL,'KEY GRAND BALLROOM','Master No.201','Kunci Ballroom (1).pdf'),
('GBR-34','Gembok Chiller Bar Banquet','Lt. 11',6,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-35','Panel Listrk Lt.10','Lt.10',1,NULL,'KEY GRAND BALLROOM','Master No.236','Kunci Ballroom (1).pdf'),
('GBR-36','Panel Listrik lantai 11 & lantai 8','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.','Kunci Ballroom (1).pdf'),
('GBR-37','Kunci Kitchen Store / Meter Air','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.338','Kunci Ballroom (1).pdf'),
('GBR-38','Uniform Room','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.','Kunci Ballroom (1).pdf'),
('GBR-39','Chiller Kitchen','Lt. 10',4,NULL,'KEY GRAND BALLROOM','Receiving','Kunci Ballroom (1).pdf'),
('GBR-4','AV Room Engineering','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.215','Kunci Ballroom (1).pdf'),
('GBR-40','Panel Hall ABCD','Lt. 11',4,NULL,'KEY GRAND BALLROOM','Master No.229','Kunci Ballroom (1).pdf'),
('GBR-41','Kunci Dance Floor','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-42','Gudang Steward','Lt.10',1,NULL,'KEY GRAND BALLROOM','Master No.237','Kunci Ballroom (1).pdf'),
('GBR-43','Kabinet DVR','Lt. 11',7,NULL,'KEY GRAND BALLROOM','Master No.2','Kunci Ballroom (1).pdf'),
('GBR-44','Ruang Mesin Lift VIP','12',1,NULL,'KEY GRAND BALLROOM','Master No.339','Kunci Ballroom (1).pdf'),
('GBR-46','Store Steward 1','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.241','Kunci Ballroom (1).pdf'),
('GBR-47','Store Steward 2','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.242','Kunci Ballroom (1).pdf'),
('GBR-48','Store Steward 3','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.243','Kunci Ballroom (1).pdf'),
('GBR-49','Store Steward 4','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.244','Kunci Ballroom (1).pdf'),
('GBR-5','VIP Room Depan & Samping','Lt. 11',2,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-50','Store Steward 5','Lt. 10',1,NULL,'KEY GRAND BALLROOM','Master No.245','Kunci Ballroom (1).pdf'),
('GBR-51','Store Housekeeping','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-52','VIP Elevator/ Penggaris +Blok Lift','Lt. 12',2,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-53','Ruang AHU Ballroom/Atas Lift VIP','Lt. 12',2,NULL,'KEY GRAND BALLROOM','Master No.333','Kunci Ballroom (1).pdf'),
('GBR-54','Rolling Door Lt.10','Lt. 10',8,NULL,'KEY GRAND BALLROOM','Master No 326,328,329,330,332','Kunci Ballroom (1).pdf'),
('GBR-55','Rolling Door Lt.11','Lt. 11',4,NULL,'KEY GRAND BALLROOM','Master No.321,322,323,324,327','Kunci Ballroom (1).pdf'),
('GBR-56','Panel Box Hidrolik','Lt. 10',2,NULL,'KEY GRAND BALLROOM','Master No.336','Kunci Ballroom (1).pdf'),
('GBR-58','Ruang Emergency Lift (Lantai 8,5,1)','Lt 8,5,1',1,NULL,'KEY GRAND BALLROOM','Duplikat No.227','Kunci Ballroom (1).pdf'),
('GBR-59','Ruang Emergency Lift (Lantai 8,5,1)','Lt 8,5,1',1,NULL,'KEY GRAND BALLROOM','Duplikat No.227','Kunci Ballroom (1).pdf'),
('GBR-6','Pintu Kayu Corridor Service','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Master No.214','Kunci Ballroom (1).pdf'),
('GBR-60','Kunci Steel Door Kitchen 10','10',1,NULL,'KEY GRAND BALLROOM','Master No.254','Kunci Ballroom (1).pdf'),
('GBR-61','Panel Listrik GI /Samping Office Security','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-62','Gudang Engineering/Dpn office kitchen','Lt 10',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-63','Kunci Box Panel LED Running Text','G',2,NULL,'KEY GRAND BALLROOM','Master No.320','Kunci Ballroom (1).pdf'),
('GBR-7','Steel Door Bar Banquet (Depan/Blakang)','Lt. 11',1,NULL,'KEY GRAND BALLROOM','Duplikat Master kosong','Kunci Ballroom (1).pdf'),
('GBR-8','Office Kitchen','Lt. 10',2,NULL,'KEY GRAND BALLROOM','Master No.247','Kunci Ballroom (1).pdf'),
('GBR-9','Panel lift hydroulik & operasional lift','Lt. 11',2,'1+1','KEY GRAND BALLROOM','Master No.230','Kunci Ballroom (1).pdf'),
('MH-146','Glass Door Reservation Room','Lt.1',1,NULL,'RESERVATION ROOM',NULL,'Kunci Master (1).pdf'),
('MK-1','Steel Door Security Office','LG',2,NULL,'MASTER KEY OFFICE SECURITY','Pintu tidak ada slot','Kunci Master (1).pdf'),
('MK-10','SDB Box Remittance','LG',1,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-100','Gembok Chiller Bar','GF',5,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('MK-101','Glass Door Garden Play Ground OUT','GF',2,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('MK-102','Glass Door Garden Play Ground IN','GF',2,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('MK-108','Kunci Gembok Pintu Exit','GF',2,NULL,'SIGNATURES','Penambahan 16 Juli 2026','Kunci Master (1).pdf'),
('MK-109','Kunci Gembok Rantai Barrier','GF',46,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('MK-11','Pintu Masuk Utama HRD','LG',1,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-110','Kunci SDB FO Nomer 20 (Master SDB)','GF',1,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('MK-111','Store Banquet Tunnel','GF',4,NULL,'LOBBY RAMAYANA',NULL,'Kunci Master (1).pdf'),
('MK-112','Rolling Door & Panel Machine Tunnel','GF',3,NULL,'LOBBY RAMAYANA',NULL,'Kunci Master (1).pdf'),
('MK-113','Kunci Emergency Exit Mushola Lobby','GF',3,NULL,'LOBBY RAMAYANA',NULL,'Kunci Master (1).pdf'),
('MK-114','Musik Room / Pantry Lobby','GF',1,NULL,'LOBBY RAMAYANA',NULL,'Kunci Master (1).pdf'),
('MK-115','Kunci Area Lobby','GF',7,NULL,'LOBBY RAMAYANA',NULL,'Kunci Master (1).pdf'),
('MK-116','Emergency Exit 1','GF',2,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-117','Emergency Exit 2','GF',2,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-118','Guest Entrance 1','GF',2,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-119','Guest Entrance 2','GF',2,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-12','Director HRD & Pantry','LG',6,'3+3','MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-120','Kunci Terrace OKU A','GF',3,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-121','Kunci Terrace OKU B','GF',3,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-122','Kunci Terrace OKU C','GF',3,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-123','Kunci Terrace OKU D','GF',3,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-124','Kunci Terrace OKU E','GF',3,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-125','Kunci Terrace OKU F','GF',3,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-126','Exit Kitchen OKU','GF',2,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-127','Exit Staircase OKU Belakang','GF',1,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-129','Store OKU','Lt.1',1,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-13','Exit Kantin ke Loading dock','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-130','Store Finance','Lt.1',1,NULL,'JAPANESE RESTAURANT (OKU)',NULL,'Kunci Master (1).pdf'),
('MK-131','Executive Office Entrance','Lt.1',3,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-132','Meeting Room 1','Lt.1',3,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-133','Meeting Room 2','Lt.1',3,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-134','Sliding Door Excom','Lt.1',1,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-135','General Manager Office','Lt.1',2,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-136','Hotel Manager Office','Lt.1',2,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-137','Dir of PR','Lt.1',1,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-139','Dir of BOT Sales','Lt.1',2,NULL,'EXECUTIVE OFFICE',NULL,'Kunci Master (1).pdf'),
('MK-14','Ex Split Room Male + Female','LG',3,'2 + 1','MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-143','Pantry Heritage Lt 1 + Showcase','Lt.1',24,'3 +21','HERITAGE ROOM',NULL,'Kunci Master (1).pdf'),
('MK-144','Restroom Male& Female Heritage Lt.1','Lt.1',6,'3+3','HERITAGE ROOM',NULL,'Kunci Master (1).pdf'),
('MK-145','Pintu Utama F&B Office & Naci Office','Lt.1',4,NULL,'HERITAGE ROOM',NULL,'Kunci Master (1).pdf'),
('MK-147','Cendana Room','Lt.2',4,NULL,'MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-148','Eboni Room','Lt.2',4,NULL,'MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-149','Damar Room','Lt.2',6,NULL,'MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-150','Angsana Room','Lt.2',2,NULL,'MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-151','Palapi Room','Lt.2',4,NULL,'MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-152','Jati Room','Lt.2',2,NULL,'MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-153','Pintu utama Executive Lounge','Lt.7',1,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-154','Pintu Kitchen Executive Lounge','Lt.7',2,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-155','Ruang Study Work','Lt.7',2,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-156','Study Work 2 Executive Lounge','Lt.7',2,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-157','Ruang Meeting Executive Lounge','Lt.7',2,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-158','Ruang Panel Executive Lounge','Lt.7',1,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-159','Toilet Depan Executive Lounge','Lt.7',3,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-16','Male Locker','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-160','Toilet Dalam Kiri+Kanan Ex Lounge','Lt.7',2,'1+1','EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-161','Kunci Break Glass Hydrant','All Area',1,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-162','Master Janitor Ramayana','Lt.7',1,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-163','Janitor West Ramayana Lt 12','Lt.12',2,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-164','Panic Button Room 818','Lt.8',8,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-165','Janitor Room 800','LT.8',1,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-166','Glass Door Gondola Rmy 9,Gns 8','Lt 8/9',1,NULL,'EXECUTIVE LOUNGE',NULL,'Kunci Master (1).pdf'),
('MK-167','Female Toilet','Lt.16',3,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-168','Male Toilet','Lt.16',3,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-169','Janitor Female Toilet','Lt.16',1,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-17','Mini training room HRD','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-170','Janitor Male Toilet','Lt.16',1,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-171','Ruang Evakuasi Heritage 1','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-172','Ruang Evakuasi Heritage 2','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-173','Pintu Besi Ruang Evakuasi Heritage 2','Lt.16',2,NULL,'HERITAGE MEETING ROOM','Connecting Parkir Mall','Kunci Master (1).pdf'),
('MK-174','Pintu Besi Gondola Depan Toilet','Lt.16',1,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-175','Pintu Besi Gondola arah PI','Lt.16',1,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-176','Pintu Ruang Hoist/Pantry depan lift','Lt 16',1,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-177','Pantry Lt.16 Ramayana','Lt.16',3,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-178','Gudang Woodgraf Ramayana','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-179','Pintu Kaca Heritage 1,1A','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-18','Staff Kantin Entrance + Kitchen kantin','LG',3,'2+1','MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-180','Pintu Kaca Heritage 1,1B','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-181','Pintu Kaca Heritage 2,2A','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-182','Pintu Kaca Heritage 2,2B','Lt.16',2,NULL,'HERITAGE MEETING ROOM',NULL,'Kunci Master (1).pdf'),
('MK-183','Single Glassdoor Samping Lift Spa','Lt.17',1,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-184','Office Manager Spa','Lt.17',1,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-185','Pintu Cowboy Kayu SPA','Lt.17',2,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-186','Sky Pool Bar','Lt.17',1,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-187','Treatment Room VIP 1','Lt.17',1,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-188','Toilet Room VIP 2','Lt.17',2,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-189','Gudang dibawah Spa','Lt.17',1,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-19','Mushola Male + Female','LG',1,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-190','Glass Door Entrance SPA (arah pavilion)','Lt.17',2,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-191','Side Entrance GYM Right & Left','Lt.17',3,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-192','Kunci glassdoor SPA to Sky Pool','Lt.17',4,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-193','Pantry GYM Kiri','Lt 17',3,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-194','Pantry GYM Kanan','Lt 17',3,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-195','Main Entrance GYM Right & Left','Lt.17',4,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-196','Restroom - Changing Room GYM','Lt.17',3,'1 + 2','SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-197','Store Pantry SPA','Lt.17',2,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-199','Kunci Exit BS03A','Lt.17',3,NULL,'SPA & GYM',NULL,'Kunci Master (1).pdf'),
('MK-2','Rak Switch CCTV GANZ','LG',6,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-20','Brewery Room Paulaner','LG',4,'2 + 2','MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-200','Store Banquet Office/Bawah tangga','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-201','Kunci gembok car lift gajah','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-202','Pintu Belakang BR C.01','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-203','Pintu Belakang BR D.02','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-204','Pintu Belakang BR B.02','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-205','Pintu Belakang BR A.02','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-206','Pintu belakang BR C.02','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-207','Pintu Belakang BR D.01','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-208','Pintu Belakang BR B.01','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-209','Pintu Belakang BR A.01','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-21','Steward Office','LG',1,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-210','Glass Door Foyer 01','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-211','Glass Door Foyer 02','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-212','Glass Door Foyer 03','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-213','Glass Door Foyer 04','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-214','Pintu Kayu Koridor Service','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-215','AV Room','GBR.11',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-216','Banquet Store','GBR.10',5,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-217','Glass Door Sales Banquet Office','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-218','Manager Sales Banquet Office','GBR.12',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-219','Gembok Chiller Bar','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-22','Clinic + Toilet Clinic','LG',4,'2 + 2','MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-220','Ruang VIP pintu depan & samping','GBR. 11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-221','Restroom Male Guest','GBR.11',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-222','Restroom Female Guest','GBR.11',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-223','Diswashing','GBR.11',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-224','CCTV Room','GBR.11',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-226','Ruang Lift lantai 12 GBR','GBR.12',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-227','Pintu Evakuasi Lift (Lantai 8,5,3,1)','GBR.11',3,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-228','Connecting CCTV Sales Banquet','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-229','Panel Room Hall A,B,C,D','GBR.11',8,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-23','Server Room IT','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-230','Kunci Panel Lift Hydroulik','GBR.11',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-231','Wood Door Samping VIP Room','GBR.11',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-236','Ex Panel Room Lt 10','GBR.10',3,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-237','Store Steward Utama','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-238','China Ware/Meter air/Lift Hydrolik','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-24','Operator Room','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-241','Store Steward nomor 1','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-242','Store Steward nomor 2','GBR.10',2,NULL,'GRAND BALLROOM','1 bengkok','Kunci Master (1).pdf'),
('MK-243','Store Steward nomor 3','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-244','Store Steward nomor 4','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-245','Store Steward nomor 5','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-247','Kitchen office','GBR.10',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-249','Canteen Staff','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-25','IT Store - Beacukai Office','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-250','Linen Room','GBR.10',3,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-251','Restroom Male Kontraktor','GBR.10',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-252','Locker Staff Male + Female','GBR.10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-253','Waste Campactor/Depan garbage 10','GBR.10',1,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-254','Steel Door kitchen 10/Area Chiller','GBR. 10',2,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-26','Purchasing Office','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-260','Double Glass Door DROP OFF','GBR.G',3,NULL,'GRAND BALLROOM',NULL,'Kunci Master (1).pdf'),
('MK-261','Container Box','BOH',1,NULL,'KUNCI MOBIL',NULL,'Kunci Master (1).pdf'),
('MK-262','Pic - Up','BOH',1,NULL,'KUNCI MOBIL',NULL,'Kunci Master (1).pdf'),
('MK-263','Cold Box','BOH',1,NULL,'KUNCI MOBIL',NULL,'Kunci Master (1).pdf'),
('MK-265','Ramayana Terrace Pintu Dome 1-4','GF',8,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-266','Ramayana Terrace Pintu Dome 5-8','GF',8,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-267','Ramayana Terrace Pintu Dome 9-12','GF',8,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-268','Ramayana Terrace Pintu Dome 13-16','GF',8,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-269','Toilet Female 1','GF',4,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-27','Beverage Store','LG',3,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-270','Toilet Female 2','GF',4,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-271','Toilet Female 3','GF',4,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-272','Toile Male 1','GF',4,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-273','Akses Ramayana Terrace dari Tunnel','GF',4,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-274','Panel Room Ramayana Terrace','GF',3,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-275','Pump Room Ramayana Terrace','GF',1,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-276','Panel Pump Room Ramayana Terrace','GF',3,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-277','Toilet Difable Ramayana Terrace','GF',3,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-278','Kunci Janitor Ramayana Terrace','GF',3,NULL,'RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-279','Kunci Gembok Portal car cheeking & Partisi Exit OKU','GF',6,'3 + 3','RAMAYANA TERRACE',NULL,'Kunci Master (1).pdf'),
('MK-28','Recycle Room (depan office Security)','LG',4,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-281','Staff Restroom','Lt.2',7,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-282','Kitchen','Lt.2',7,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-283','Store Butcher','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-284','Beer Cold','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-285','Hydrant Box','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-286','AHU Room','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-287','IT Room','Lt.2',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-288','Restroom','Lt.2',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-289','Room Key','Lt.2',6,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-29','F & B Store + Ciller','LG',3,'2 + 1','MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-290','VIP Room','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-291','Folding Door VIP','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-292','Main Entrance Door','Lt.2',3,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-293','Window Glass Door','Lt.2',16,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-294','AV Room','Lt.2',6,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-295','Paulaner Stub','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-296','Janitor Paulaner','Lt.2',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-297','Store Paulaner','Lt.1',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-298','Bangker Paulaner Bar','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-299','Kempi Deli Pintu Double A-B','Lt.2',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-3','Panel CCTV Pusat Astina','LG',13,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-30','General Store','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-300','Kempi Deli Pintu Double C-D','Lt.2',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-301','Kempi Deli Pintu Kitchen','Lt.2',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-302','Kunci Jendela Smooking Paulaner','Lt 2',15,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-31','Receiving Office','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-32','Banquet Store (Depan Sec Office)','LG',3,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-320','Master Key LED Running Text','GBR/LG',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-321','Rolling Door Food Lift 2 Lt.11','GBR.11',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-322','Rolling Door Food Lift 1 Lt.11','GBR.11',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-323','Rolling Door Steward 2 Lt. 11','GBR.11',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-324','Rolling Door Steward 1 Lt. 11','GBR.11',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-325','Pintu Garbage Lt.10','GBR.10',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-326','Rolling Door Garbage 1 Lt.10','GBR.10',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-327','Rolling Door Loading Car 3 Lt.11','GBR.11',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-328','Pintu Rooling door menuju chiller Lt.10','GBR.10',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-329','Rolling Door Garbage 2 Lt.10','GBR.10',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-33','HK Office','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-330','Rolling Door Loading Car 1 Lt.10','GBR.10',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-331','Loading Car 2 Lt.10','GBR.10',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-332','Rolling Door Kitchen Lt.10','GBR.10',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-333','AHU lantai 12 (Atas lift VIP)','GBR.12',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-335','Chiller Box 2/2 Lt.10','GBR.10',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-337','Kerangkeng GBR','GBR.10',3,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-338','Kunci store Kitchen (meter air)','GBR.10',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-339','Kunci Ruang Mesin Lift VIP Lt.12','GBR.12',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-34','Exc. HK Office','LG',1,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-341','Kunci Block Lift VIP GBR','GBR.11',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-347','Gudang JCI Karpet (Basement Mall)','B1 Mall',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Ruangan dibongkar 1 Juli 2026','Kunci Master (1).pdf'),
('MK-35','HK Order Taker','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-351','Steel Door Depan Lift Resident','LG',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-352','Steel Door Sebelum Staff Entrance','LG',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-353','Steel Door Samping Security Office','LG',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-354','Steel Door Samping Receiving','LG',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-355','Exit Depan kantin bawah','LG',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-356','Exit depan kantin atas','LG',4,NULL,'PAULANER BRAUHAUS - KEMPIDELI',NULL,'Kunci Master (1).pdf'),
('MK-357','Stell Door Staff Entrance Sisi Dalam','LG',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-358','Pintu Besi Ram Naik Loading Dock','LG',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-359','Pintu Besi Dari Diswashing Ke Receiving','LG',2,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-36','Lost and Found','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-360','Pintu Box Rolling Door Receiving 1','LG',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-361','Pintu Box Rolling Door Receiving 2','LG',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-362','Pintu Box Rolling Door Receiving 3','LG',1,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-363','Pintu Besi Connecting Commisari & Butcher','LG',3,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-364','Emergency Exit Pastry','LG',3,NULL,'PAULANER BRAUHAUS - KEMPIDELI','Tambahan 23/7/2026','Kunci Master (1).pdf'),
('MK-37','HK Store','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-38','HK Uniform','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-39','Connecting HK Linen','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-4','Memory Box X-ray + Kunci Xray','LG',4,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-40','Office Manager Laundry','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-41','Office Order Taker Laundry','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-42','Main Entrance Laundry','LG',2,NULL,'HK & LAUNDRY',NULL,'Kunci Master (1).pdf'),
('MK-43','Engineering Workshop','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-44','PABX','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-45','Engineering Office','LG',3,NULL,'ENGINEERING','Tidak ada silinder pintu','Kunci Master (1).pdf'),
('MK-46','Battery Room','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-47','Engineering Panel','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-48','Bakery','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-49','Pastry','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-5','Kunci Walktrouht','LG',14,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-50','Comisary','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-51','Main Kitchen Double','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-52','Steward Store','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-53','Exc. Chef Office','LG',1,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-54','Wedding Cake (Samping pastry)','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-55','gembok Chiller Meet','LG',4,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-56','Store Glass Steward','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-57','Kunci Exit Male & Female Locker','LG',3,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-58','Kunci Female Split Room','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-59','Kunci Male Split Room','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-6','Kunci Shaff','LG',6,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-60','Pintu Shaff Basement + Laundry','BS',4,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-61','Boiler Room','BS',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-62','Steel Door samping training room','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-63','Training Room LG/Depan Lift Service','LG',1,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-64','Kunci Finance Store (Depan Lift LG)','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-65','Rolling Door store banquet','LG',2,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-66','Kunci SDB Outlet (Dimeja Dian)','LG',6,NULL,'ENGINEERING',NULL,'Kunci Master (1).pdf'),
('MK-67','Master Key SDB A - B','LG',2,NULL,'ACCOUNTING',NULL,'Kunci Master (1).pdf'),
('MK-68','Master Key SDB A - B','LG',1,NULL,'ACCOUNTING',NULL,'Kunci Master (1).pdf'),
('MK-69','Master Key SDB A','LG',1,NULL,'ACCOUNTING',NULL,'Kunci Master (1).pdf'),
('MK-7','CCTV Room Hotel','LG',6,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-70','Glass Door VIP Ganesha','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-71','Glass Door Entrance Bali Room','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-72','Pantry HK Bali Room','GF',2,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-73','Toilet Male Bali Room','GF',2,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-74','Toilet Female Bali Room','GF',2,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-75','Glass Door In Bali Room','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-76','Bar Chiller Bali Room','GF',2,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-77','Pintu ruang AV Belakang','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-78','Pantry Nirwana','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-79','Kunci Gembok Bali Room to Mall','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-8','Exit Door','LG',2,NULL,'MASTER KEY OFFICE SECURITY',NULL,'Kunci Master (1).pdf'),
('MK-80','Pintu besi menuju belakang Baliroom','GF',1,NULL,'BALI ROOM',NULL,'Kunci Master (1).pdf'),
('MK-81','Business Centre (Lobby Ramayana)','GF',2,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-82','Panic Button FO','GF',1,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-83','Glass Door Pavilliun depan BC','GF',2,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-84','Pintu kayu SDB lama /Samping lift','GF',1,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-85','Toilet Male/Female Ramayana','GF',2,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-86','Single glass door depan swett boutiq','GF',2,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-87','Luggage Room Depan Toilet','GF',1,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-89','Glass Door Tunnel Mall (TTR)','GF',4,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-9','Master PANEL','LG',1,NULL,'MASTER KEY OFFICE SECURITY','Penambahan 1 Juli 2026','Kunci Master (1).pdf'),
('MK-90','Sweet Boutiq','GF',5,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-91','Double Glass Door Lobby Ramayana','GF',2,NULL,'LOBBY',NULL,'Kunci Master (1).pdf'),
('MK-95','Panel Room Mushola Tamu','GF',3,NULL,'BUSINESS CENTRE',NULL,'Kunci Master (1).pdf'),
('MK-96','Mahoni Meeting Room','GF',2,NULL,'BUSINESS CENTRE',NULL,'Kunci Master (1).pdf'),
('MK-97','Ulin Meeting Room','GF',1,NULL,'BUSINESS CENTRE',NULL,'Kunci Master (1).pdf'),
('MK-98','Glass Door Play Ground Signatures','GF',2,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('MK-99','Gudang Signature/Belakang Baliroom','GF',2,NULL,'SIGNATURES',NULL,'Kunci Master (1).pdf'),
('PB-10','Main Entrance','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-12','Store Lantai 1 East mall','Lantai 1 EM',2,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-13','Rolling Door Lift 1','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-14','Rolling Door Lift 2','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-15','Rolling Door Lift 3','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-16','Rolling Door Lift 4','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-17','AHU Room Samping stage','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-18','Toilet Staff','Lantai 2 EM',4,NULL,'KEY PAULANER','Silinder seret','Kunci Paulaner (1).pdf'),
('PB-2','Ruang VIP Luar','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-20','Ruang janitor Belakang Hydrant','Lantai 2 EM',2,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-21','Ruang Loker Staff','Lantai 2 EM',3,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-22','Kunci Loker','Lantai 2 EM',2,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-23','Audio Visual','Lantai 2 EM',5,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-24','USB Lighting','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-25','Server IT','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-26','Kunci Kaca Teras (Arah Luar)','Lantai 2 EM',15,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-3','Beer Cold Room','Lantai 2 EM',1,NULL,'KEY PAULANER','silinder rusak/ pakai gembok','Kunci Paulaner (1).pdf'),
('PB-30','Kunci partisi Kempi Deli','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-4','Pintu Teras 1','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-5','Pintu Teras 2','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-6','Pintu Teras 3','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-7','Pintu Teras 4','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-8','Pintu Exit','Lantai 2 EM',2,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('PB-9','Pintu dapur','Lantai 2 EM',1,NULL,'KEY PAULANER',NULL,'Kunci Paulaner (1).pdf'),
('SE-1','Security Office','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-10','Finance Store (Samping Training Room)','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-11','Executive Chef Office','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-12','Beverage Store','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-13','Chemical Room','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-14','F & B Store','LG',5,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-15','Banquet Store (Depan Security)','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-16','Uniform Linen','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-17','Clinik','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-18','Server / IT Room','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-19','Operator Room','LG',1,'1+Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-2','Purchasing','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-20','Laundry Office','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-21','OKU Restaurant','LG',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-22','Main Entrance Laundry','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-23','Connecting HK Office Linen','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-24','Akses Gondola Ramayana Lt.9','LT.9',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-25','Projeck Kantin P6 East Mall','P6 EM',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-26','Box Rolling Door Receiving','LG',3,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-27','Pintu Besi Ram Loading Dock','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-28','Garden Play Ground Signatures','GF',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-29','Pintu Besi dari Diswashing ke Receiving','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-3','Rolling Door Garbage','LG',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-30','Kunci Pintu Gondola','LT.16',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-31','Gudang Projeck CCTV','LG',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-32','GBR','LT.10&11',9,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-33','Kunci Pantry HK Lobby','GF',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-34','Store Signatures','GF',4,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-35','Recycle Room','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-36','Wood Door Sky Pool Bar','LT.17',5,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-37','Pantry to SPA','LT.17',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-38','Entrance to SPA','LT.17',13,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-39','Changing Room SPA','LT.17',5,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-4','Glass Door Lt. 9, 8 Gns dan Room 832','Lt.9 & 8',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-40','Main Entrance SPA to Sky Pool','LT.17',3,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-41','Pantry Nirwana Lounge','GF',14,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-43','Wine Chiller','GF',3,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-44','Main Entrance GYM','LT.17',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-45','Side Door GYM','LT.17',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-46','Executive Lounge','LT.7',12,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-47','IT Store / Loading Dock','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-48','Store Steward','Lt.10 GBR',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-49','Store Steward','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-5','Entrance Bundaran Café','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-50','Dance Floor Baliroom','GF',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-51','Bar Chiller Baliroom','GF',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-52','Split Room (Male & Female)','LG',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-53','Kunci Box Tissu Staff Entrance','LG',3,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-54','Sweet Boutiq (Lobby)','GF',2,NULL,'KEY STAFF ENTRANCE HOTEL','Di keep staff penyewa','Kunci Staff Entrance (1).pdf'),
('SE-55','Ex Koperasi Room','LG',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-56','Reservasi Room','LT.1',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-57','All Baliroom','GF',4,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-59','Steel Door Baliroom Kitchen','GF',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-6','Receiving Office','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-60','Store Paulaner Lt.6 East Mall','LT.6 EM',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-62','OKU restaurant','GF',4,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-63','OKU Acces Card Operasional','GF',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-64','Acces Card IT Room (Nurodin+Firman)','LG',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-65','Paulaner Bar','LT.2EM',18,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-66','Acces Card Split Room Male','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-67','Acces Card Split Room Female','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-68','Kempi Deli','LT.2EM',5,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-69','Main Kitchen','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-7','Mushola BOH','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-70','Store OKU','GF',8,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-71','Butcher','LG',7,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-72','Glass Door Cendana','LT.2',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-73','Glass Door Eboni','LT.2',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-74','Glass Door Damar','LT.2',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-75','Glass Door Angsana','LT.2',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-76','Glass Door Palapi','LT.2',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-77','Glass Door Jati','LT.2',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-78','Glass Door Heritage 1','LT.16',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-79','Glass Door Heritage 2','LT.16',2,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-8','Human Resources Office (HR)','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-80','Laci Business Center','GF',4,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-82','Mobil B 9313 UP','Mobil',1,'1+STNK','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-83','Mobil B 9315 UP','Mobil',1,'1+STNK','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-84','Mobil B 9321 UP','Mobil',1,'1+STNK','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-85','Mobil B 2286 SKM','Mobil',1,'1+STNK','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-86','Mobil 1850 IS','Mobil',1,'1+STNK','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-87','Mobil 1770 PFD','Mobil',1,'1+STNK','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-88','Acces Card Floor Warden 2','All Area',1,'1 Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-89','Acces Card Floor Warden 3','All Area',1,'1 Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-9','Training Room /Dpn Lift','LG',1,NULL,'KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-91','Acces Card Floor Warden 4','All Area',1,'1 Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-92','Acces Card Floor Warden 5','All Area',1,'1 Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-93','Acces Card Floor Warden 6','All Area',1,'1 Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf'),
('SE-94','Acces Card Floor Warden 7','All Area',1,'1 Acces','KEY STAFF ENTRANCE HOTEL',NULL,'Kunci Staff Entrance (1).pdf')
) v(key_number,key_description,floor,quantity,quantity_detail,category,remarks,source_document)
cross join (select id from public.properties where property_code='HIKJ' and is_active=true limit 1) p
on conflict (property_id,key_number) do nothing;
